"""Manifest generation and application.

A manifest is the same shape the sibling audit lanes emit:

    {"delete": ["assets/.../stale.geo.json", ...],
     "write":  {"assets/.../fixed.json": "<file content>", ...},
     "notes":  ["free text", ...]}

`packlint fix` applies one to a pack zip and writes a NEW zip. Never in place:
the pack that is live is the pack that is live, and a half-written zip is how a
deploy turns into an outage.
"""

from __future__ import annotations

import json
import os
import shutil
import zipfile
from typing import Any

from packlint import findings as F
from packlint.validate import Result


def build_manifest(result: Result, include: tuple[str, ...] = (F.RESIDUE,)) -> dict[str, Any]:
    """Collect the deletions the findings propose, grouped by rule."""
    deletes: dict[str, list[str]] = {}
    for finding in result.findings:
        if finding.severity not in include:
            continue
        for path in finding.suggest_delete:
            deletes.setdefault(path, []).append(f"{finding.rule}: {finding.message}")

    notes = [
        "Generated by eclipse-pack-lint. Every entry is a SUGGESTION - read the reasons "
        "before applying.",
        "Severity classes included: " + ", ".join(include),
        "Apply with: python -m packlint fix --pack <pack.zip> --manifest <this file> "
        "--out <new.zip>",
    ]
    return {
        "delete": sorted(deletes),
        "write": {},
        "reasons": {path: reasons for path, reasons in sorted(deletes.items())},
        "notes": notes,
    }


def apply_manifest(pack_path: str, manifest: dict[str, Any], out_path: str) -> dict[str, Any]:
    """Write a new zip with the manifest's deletions and writes applied."""
    if os.path.abspath(pack_path) == os.path.abspath(out_path):
        raise ValueError("refusing to rewrite the pack in place - pass a different --out")
    if os.path.exists(out_path):
        raise ValueError(f"--out already exists: {out_path}")

    delete = set(manifest.get("delete") or [])
    write: dict[str, str] = dict(manifest.get("write") or {})

    deleted: list[str] = []
    replaced: list[str] = []
    added: list[str] = []
    missing = set(delete)

    tmp_path = out_path + ".partial"
    try:
        with zipfile.ZipFile(pack_path) as src, zipfile.ZipFile(
            tmp_path, "w", zipfile.ZIP_DEFLATED
        ) as dst:
            for info in src.infolist():
                name = info.filename.replace("\\", "/")
                if info.is_dir():
                    continue
                if name in delete:
                    deleted.append(name)
                    missing.discard(name)
                    continue
                if name in write:
                    dst.writestr(name, write.pop(name).encode("utf-8"))
                    replaced.append(name)
                    continue
                dst.writestr(info, src.read(info))
            for name, content in write.items():
                dst.writestr(name, content.encode("utf-8"))
                added.append(name)
        shutil.move(tmp_path, out_path)
    finally:
        if os.path.exists(tmp_path):
            os.remove(tmp_path)

    return {
        "out": out_path,
        "deleted": sorted(deleted),
        "replaced": sorted(replaced),
        "added": sorted(added),
        "delete_not_found": sorted(missing),
    }


def load_manifest(path: str) -> dict[str, Any]:
    with open(path, "r", encoding="utf-8-sig") as fh:
        manifest = json.load(fh)
    if not isinstance(manifest, dict):
        raise ValueError("manifest must be a JSON object")
    return manifest
